# Generated by Django 4.2.30 on 2026-06-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_profit_accrual',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profit_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
