# Generated by Django 4.2.30 on 2026-06-25 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_profit_accrual_user_profit_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='vip_upgrades/')),
                ('amount', models.DecimalField(decimal_places=8, default=200.0, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_upgrades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
