# Generated by Django 4.2.30 on 2026-06-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_vipupgraderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_investment_override',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profit_accrued_override',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_bonus_override',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
