# Generated by Django 4.2.30 on 2026-07-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_password_reset_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_automation_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
