# Generated by Django 4.2.30 on 2026-08-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=100)),
                ('wallet_address', models.CharField(max_length=255)),
                ('network', models.CharField(help_text='e.g. ERC20, TRC20, BEP20', max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='Only one wallet can be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_upgrade_fee', models.DecimalField(decimal_places=2, default=200.0, max_digits=20)),
                ('company_wallet_address', models.CharField(default='0x71C7656EC7ab88b098defB751B7401B5f6d8976F', max_length=255)),
                ('wallet_network', models.CharField(default='ERC20', max_length=50)),
                ('conversion_fee_pct', models.DecimalField(decimal_places=2, default=1.0, help_text='Default 1.00 for 1%', max_digits=5)),
                ('enable_currency_converter', models.BooleanField(default=True)),
                ('enable_vip_upgrade', models.BooleanField(default=True)),
                ('enable_withdrawals', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
