# Generated by Django 4.2.30 on 2026-08-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='method',
            field=models.CharField(choices=[('BANK', 'Bank Transfer'), ('CRYPTO', 'Cryptocurrency'), ('PAYPAL', 'PayPal')], default='CRYPTO', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
