# Generated by Django 4.2.30 on 2026-06-24 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID_CARD', 'ID Card'), ('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', "Driver's License"), ('PROOF_OF_ADDRESS', 'Proof of Address'), ('SELFIE', 'Selfie'), ('SSN', 'SSN')], max_length=20)),
                ('document_url', models.URLField(max_length=500)),
                ('document_number_encrypted', models.CharField(blank=True, db_column='document_number', max_length=255)),
                ('issued_country', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.admin')),
            ],
        ),
    ]
