# Generated by Django 4.2.30 on 2026-07-01 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='amount_per_payout',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='distribution_frequency',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MATURITY', 'At Maturity'), ('CUSTOM_6H', 'Every 6 Hours'), ('CUSTOM_12H', 'Every 12 Hours')], default='DAILY', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='expected_profit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='expected_profit_type',
            field=models.CharField(choices=[('PERCENT', 'Percentage'), ('ABSOLUTE', 'Absolute Amount')], default='PERCENT', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='is_automated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='last_payout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='next_payout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='payouts_made',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_payouts_expected',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='investment',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=20),
        ),
    ]
